[project]
name = "genlm-control-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "genlm-control>=0.2.2",
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]
